# NUMPY: Slicing/Stacking and Indexing with Boolena Arrays

# Topics:
1. Indexing and Slicing
2. Iterating through arrays
3. Stacking together two arrays
4. Indexing with boolean arrays

# Slicing

In [1]:
import numpy as np

In [2]:
n = [6,7,8]

In [3]:
n[0:2]

[6, 7]

In [4]:
n[-1]

8

In [5]:
#For numpy array

In [6]:
a = np.array([6,7,7])

In [7]:
a[0:2]

array([6, 7])

In [8]:
a[-1]

7

In [9]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]]) #multidimensional array
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [10]:
a[1,2]  #1st row second element

3

In [11]:
a[0:2]  #0th and 1st row

array([[6, 7, 8],
       [1, 2, 3]])

In [12]:
a[0:2,2]

array([8, 3])

In [14]:
a[-1]

array([9, 3, 2])

In [15]:
a[-1,0:2]

array([9, 3])

In [16]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [17]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [18]:
#flatten the array
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [ ]:
#stacking two arrays together

In [19]:
a = np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [20]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
np.vstack((a,b))  #stacked vertically

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
np.hstack((a,b))  #stack horizontally

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [24]:
a = np.arange(30).reshape(2,15)

In [25]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [27]:
result = np.hsplit(a,3)

In [28]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [29]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [30]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [31]:
result = np.vsplit(a,2)

In [32]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [33]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
a = np.arange(12).reshape(3,4)

In [37]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])